---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: logcollector
  namespace: openshift-logging

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:privileged:logcollector'
  namespace: openshift-logging
subjects:
  - kind: ServiceAccount
    name: logcollector
    namespace: openshift-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
