kind: ConfigMap
apiVersion: v1
metadata:
  name: rsyslogd-config
  namespace: openshift-logging
data:
  rsyslog.conf: |2
    global(LocalHostName=`echo $NODENAME`)
    global(workDirectory="/var/tmp")

    module(load="imuxsock"    # provides support for local system logging (e.g. via logger command)
           SysSock.Use="off") # Turn off message reception via local log socket; 
                              # local messages are retrieved through imjournal now.
    module(load="imjournal"   # provides access to the systemd journal
           StateFile="imjournal.state"  # File to store the position in the journal
           Remote="on")                 # Also read logs from the host
    module(load="builtin:omfile" Template="RSYSLOG_TraditionalFileFormat")
    module(load="imfile" PollingInterval="10")
    
    template(name="kube-log-forwarding" type="list") {
        constant(value="<")
        property(name="pri")
        constant(value=">")
        property(name="timestamp" dateFormat="rfc3339")
        constant(value=" ")
        property(name="hostname")
        constant(value=" ")
        property(name="syslogtag" position.from="1" position.to="32")
        constant(value=": ")
        property(name="$.pod")
        constant(value=" ")
        property(name="$.namespace")
        constant(value=" ")
        property(name="$.container")
        constant(value=" ")
        property(name="msg" spifno1stsp="on" )
        property(name="msg")
        }
    
    # Gather Kubernetes Metadata from the filename
    ruleset(name="container_logs")
    {
        set $.pod_namespace_container = re_extract($!metadata!filename, "/var/log/containers/(.*).log", 0, 1, "");
        set $.pod = field($.pod_namespace_container, "_", 1);
        set $.namespace = field($.pod_namespace_container, "_", 2);
        set $.container = field($.pod_namespace_container, "_", 3);
        
        action(type="omfwd"
            target  = `echo $LOGSERVER`
            port    = "514"
            protocol= "udp"
            template= "kube-log-forwarding"
            )
        stop
    }
    
    # Follow the container log files
    input(type="imfile" file="/var/log/containers/*.log"
           tag="kubernetes"
           Severity="info"
           Facility="local0"
           ruleset="container_logs")
    
    # Basic forwarding to remote syslog server
    ruleset(name="to_remote")
    {
        action(type="omfwd"
            target  = `echo $LOGSERVER`
            port    = "514"
            protocol= "udp"
            )
    }
    call to_remote
