kind: ConfigMap
apiVersion: v1
metadata:
  name: rsyslogd-config
  namespace: openshift-logging
data:
  rsyslog.conf: "module(load=\"imuxsock\" \t  # provides support for local system logging (e.g. via logger command)\n       SysSock.Use=\"off\") # Turn off message reception via local log socket; \n\t\t\t  # local messages are retrieved through imjournal now.\nmodule(load=\"imjournal\" \t    # provides access to the systemd journal\n       StateFile=\"imjournal.state\"  # File to store the position in the journal\n       Remote=\"on\")                 # Also read other machine's journals\nglobal(workDirectory=\"/tmp\") module(load=\"builtin:omfile\" Template=\"RSYSLOG_TraditionalFileFormat\")\n*.info;mail.none;authpriv.none;cron.none                /tmp/messages\n"
