kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: rsyslogd
  namespace: openshift-logging
spec:
  selector:
    matchLabels:
      app: rsyslogd
  template:
    metadata:
      labels:
        app: rsyslogd
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: rsyslogd
        env:
          - name: SYSLOGD_OPTIONS
            value: '-f /config/rsyslog.conf'
        image: registry.redhat.io/rhel8/rsyslog
        command: ["/usr/sbin/rsyslogd","-n","-f","/config/rsyslog.conf"]
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 1Gi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: rsyslogd-config
          readOnly: true
        - mountPath: /var/log/journal
          name: varlogjournal
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: logcollector
      serviceAccountName: logcollector
      volumes:
      - configMap:
          defaultMode: 420
          name: rsyslogd-config
        name: rsyslogd-config
      - hostPath:
          path: /var/log/journal
          type: ""
        name: varlogjournal
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
