---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00_namespace.yml
  - 02_rbac.yml
  - 05_configmap-rsyslogd-config.yaml
  - 05_configmap-rsyslog-connector.yaml
  - 10_daemonset-rsyslogd.yaml
